name: Lint Test and Deploy Workflow
on:
  issues:
    types: [opened,closed,edited,reopened]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Github Context Output
        run: echo "${{toJSON(github.event)}}"